### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by bowring** [JsonHrdwick/BeverageProject-gradle#1]
- [x] research gradle and its history (make files, ant, maven ...) (integrated into IJ)
- [x] create new project using gradle and put your code in it 
- [x] research JUnit testing (integrated into IJ)
- [x] migrate Driver.main functionality to JUnit tests
